const Clinking = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f37b/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f37b/512.gif"
      alt="🍻"
      width="400"
      height="400"
    />
  </picture>
);
const Dancer = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f483_1f3fb/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f483_1f3fb/512.gif"
      alt="💃"
      width="400"
      height="400"
    />
  </picture>
);
const Dragon = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f409/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f409/512.gif"
      alt="🐉"
      width="400"
      height="400"
    />
  </picture>
);
const Flying = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f6f8/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f6f8/512.gif"
      alt="🛸"
      width="400"
      height="400"
    />
  </picture>
);
const Kissing = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f618/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f618/512.gif"
      alt="😘"
      width="400"
      height="400"
    />
  </picture>
);
const Lauphing = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f606/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f606/512.gif"
      alt="😆"
      width="400"
      height="400"
    />
  </picture>
);
const Loudly = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f62d/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f62d/512.gif"
      alt="😭"
      width="400"
      height="400"
    />
  </picture>
);
const Mind = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f92f/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f92f/512.gif"
      alt="🤯"
      width="400"
      height="400"
    />
  </picture>
);
const Racehorse = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f40e/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f40e/512.gif"
      alt="🐎"
      width="400"
      height="400"
    />
  </picture>
);
const Winky = (
  <picture>
    <source
      srcset="https://fonts.gstatic.com/s/e/notoemoji/latest/1f61c/512.webp"
      type="image/webp"
    />
    <img
      src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f61c/512.gif"
      alt="😜"
      width="400"
      height="400"
    />
  </picture>
);
export {
  Clinking,
  Dancer,
  Dragon,
  Flying,
  Kissing,
  Lauphing,
  Loudly,
  Mind,
  Racehorse,
  Winky,
};
